### ISSUE TITLE
Coordinates throw error in contamination tool

### ISSUE THREAD

**Issue by hover2pi** [ExoCTK/exoctk#225]
From Jeff Chamblee:

If I use https://exoctk.stsci.edu/contam_visibility and I put in RA: 04:29:38.990, Dec: +22:52:57.80, press either Calculate buttons I get error:

"Something's amiss...
Your chosen tool did not complete for the following reason:
The following error occurred: index 366 is out of bounds for axis 0 with size 36"

The target is K2-136 b, which resolves correctly but then gets the same error when you click the button.

**Comment by jaymedina** [comment]
I just re-created this error and it looks like it's an `IndexError` on line 166 of `visibilityPA.py`'s `checkVisPA()` function. I tried running these coordinates on my `using_gtvt()` function, and it works fine. Since we'll essentially be replacing `checkVisPA()` with `using_gtvt()` as part of the visibility expansion, I'll mark this issue as Solved once I finish implementing the expansion to the website. 

Here is what my visibility output looks like w/ `using_gtvt()`:
<img width="812" alt="image" src="https://user-images.githubusercontent.com/32107699/54157006-cddc0680-441d-11e9-96c8-18488fbd7c95.png">

**Comment by bourque** [comment]
@jaymedina Note that I just talked with Jeff Chamblee and he warned me that changing the name of the function that is being called to do this would break things on their end, so we should either make sure to use the same function names or communicate with them that a change needs to be made.

**Comment by hover2pi** [comment]
Awesome. Thanks @jaymedina !

**Comment by jaymedina** [comment]
@bourque ah yeah, in this expansion, some of the functions will be getting a name change (since they've been called `soss[Fill in the blank]`, but will no longer be just for SOSS mode). We'll have to communicate that to people who have `ExoCTK` as a dependency in their own projects.

**Comment by jaymedina** [comment]
I'll go ahead and mark this issue as `Closed` since my visibility PR was merged, and this is no longer a problem with `using_gtvt()`. 

Side note, we should update Jeff and the ExoMAST group to notify them about the updates: 
- `checkVisPA()` is now `using_gtvt()` 
- The required input parameters are now: `ra`, `dec`, and `instrumentName`, with `instrumentName` being case sensitive (it can either be: NIRISS, NIRCam, NIRSpec, MIRI)
