### ISSUE TITLE
Contamination & Visibility Calculator Bugs

### ISSUE THREAD

**Issue by kevin218** [ExoCTK/exoctk#285]
- [x] When I click the "Save" button, the Target Contamination Bokeh plot is saved in 8 separate pieces.  Can we make this 1 figure? 
- Temporary solution: Removed `save` button. 
- It is unfortunately a known issue that `bokeh` saves these all as different plots because they are all rendered as separate `HTML` objects. I think what might be possible is instead of saving the plot, saving an image of the entire html page. I don't know if this is too hacky to be a desirable solution.
- [x] The tool doesn't display the same contamination overlap results as before (previously calculated in 2017).  
- [x] The semi-transparent regions are missing for the inaccessible PAs. 
- Turns out these were purposefully disabled at some point. I'm not sure how to fix them.
- ~@kevin218 Can you give an example here -- I'm not sure I understand what you mean?~
- [x] When the target visibility crosses 360 degrees, there is a green vertical region extending down to 0 degrees. 
- There is definitely a better way to do this (it probably involves plotting lines individually) but for now I've replaced the nominal, max, and min values with a circle plot so it plots point and doesn't try to make lines over discontinuities. 
- [x] For the Visibility Bokeh plot, the default PA range should be 0 to 360 degrees.

**Comment by jaymedina** [comment]
Hey @kevin218 !

1. Good catch! I'll take a look at this now. 
2. The new Contam Overlap tool uses the JWST General Target Visibility Tool which has its own ephemeris. So this might be due to some slight differences between the ephemeris they use and the old one we used. I will take a look at it today. 
3. I'm not sure I understand this one - do you mean why there is no light green bar in the white spaces? The light green bar shows you the minimum and maximum PA ranges during those windows when the target is accessible. Else, the target can't be seen regardless of what PA is used. 
4. Yep, I saw this before v0.3 release and it doesn't look like a straightforward fix to it. We settled on adding the note `Note that it is possible for the Minimum Aperture PA to be larger than the Maximum Aperture PA if the maximum boresight roll takes the Maximum Aperture PA beyond 360 degrees.` under the bokeh plot to explain the vertical bar. I do agree that it's kind of an eyesore when it does show up, so I'll take a look at it again today & see if I can find an immediate solution. 

The deadline to merge all PRs for v0.4 release is before COB today. Anything that's not addressed in this issue before then will be addressed before v0.5 release.

**Comment by kevin218** [comment]
2017: 
<img width="1181" alt="Screen Shot 2019-08-08 at 10 51 44 AM" src="https://user-images.githubusercontent.com/21340541/62713415-b4d68200-b9ca-11e9-81d1-41692661bb21.png">
2019: 
![contamination-wasp-63_PA0-360](https://user-images.githubusercontent.com/21340541/62713457-c586f800-b9ca-11e9-9736-aca19344a2bd.png)

**Comment by jaymedina** [comment]
[Referring to 2.]

Ok, so it does look like the ephemeris GTVT uses is slightly different from ours: https://github.com/spacetelescope/jwst_gtvt/blob/master/jwst_gtvt/horizons_EM_jwst_wrt_sun_2020-2024.txt

I don't have knowledge on how the ephemeris is calculated, but I would vote for sticking with the GTVT one since it has data until 2024.

**Comment by kevin218** [comment]
@jaymedina The new target visibility plot with GTVT times looks good.  I'm concerned about the contamination plot (see above comparison).

**Comment by kevin218** [comment]
David Lafreniere's contamination overlap tool is available here: http://maestria.astro.umontreal.ca/niriss/SOSS_cont.

Here is the output for WASP-63:
![bokeh_plot](https://user-images.githubusercontent.com/21340541/62734577-55db3200-b9f7-11e9-8718-431995641f2a.png)
