### ISSUE TITLE
Enable contam overlap with MIRI

### ISSUE THREAD

**Issue by bourque** [ExoCTK/exoctk#346]

**Comment by jaymedina** [comment]
Update: 
- There was some contamination "pile up" for MIRI LRS 
![image](https://user-images.githubusercontent.com/32107699/78177183-b5c19580-742b-11ea-9dfc-91c97444d392.png)

- I fixed it by making the contamination calculator ignore the rows that had just pure background:
![image](https://user-images.githubusercontent.com/32107699/78177257-d7228180-742b-11ea-808a-bf7c09b9511c.png)

- Next issue is verifying that all the contamination is there because it looks like MIRI has way less contamination compared to its NIRCam equivalent for this target: 
![image](https://user-images.githubusercontent.com/32107699/78177309-ef929c00-742b-11ea-88d0-916b221a18e3.png)

@hover2pi
