### ISSUE TITLE
Limb-darkening `LDC` class/`modelgrid` calls the wrong data path

### ISSUE THREAD

**Issue by nespinoza** [ExoCTK/exoctk#382]
Hey everyone,

Something is going on with `modelgrid` and the `LDC` class, in that it tries to load data from `/internal/data1/exodeploy/exoctk_data/modelgrid/` instead of the EXOCTK user-defined data path. Error is easy to reproduce by doing the following:

```
from exoctk.limb_darkening import limb_darkening_fit as lf
ldcs = lf.LDC(model_grid='ATLAS9')
```

Outputs the following:

`330 models loaded from /internal/data1/exodeploy/exoctk_data/modelgrid/ATLAS9/`

Despite the fact I don't have a folder `/internal`. Indeed, when doing `os.environ.get('EXOCTK_DATA')` I get `/Users/nespinoza/exoctk_data/` --- the correct variable for the data path.

I did some digging, and it appears the problem is in `modelgrid`. If you do: 

```
from exoctk import modelgrid
mg = modelgrid.ATLAS9(resolution=700)
```

You get `330 models loaded from /internal/data1/exodeploy/exoctk_data/modelgrid/ATLAS9/`. It seems the data path `/internal/data1/exodeploy/exoctk_data/modelgrid/` is hard-coded somewhere, but I can't seem to find it. I found this bug while trying to run `awesimsoss` (the NIRISS SOSS simulator --- https://github.com/spacetelescope/awesimsoss/), whose limb-darkening calculations crash because of this in my machine.

I'm tagging @hover2pi on this one as I have a hunch he'll know what is going on here!

Thanks in advance!

Néstor

**Comment by hover2pi** [comment]
@nespinoza Yes, I think I know what the issue is. The first time you load the models, it takes a few minutes but then stores a serialized table with the path to the files so it's much faster afterward. I think my PR #381 had the pickle in it, which would cause this issue for everyone except the Web app.

I think what I'll do is have it run a quick check when `modelgrid` is called to see if the `LDC.model_grid.path` matches the user's `EXOCTK_DATA` path and regenerate the pickle if there is a mismatch.

Thanks for the Issue!

**Comment by hover2pi** [comment]
Pretty confident this is fixed in #383

**Comment by hover2pi** [comment]
@nespinoza Can you confirm this is fixed? It works on my machine. Thanks!

**Comment by nespinoza** [comment]
Yup, it did --- closing it; thanks!
