### ISSUE TITLE
error: scipy 1.5.0 is installed but scipy<1.2 is required by {'platon'}

### ISSUE THREAD

**Issue by thommevans** [ExoCTK/exoctk#388]
I'm trying to install ExoCTK on my local computer. When I run "python setup.py install" I get the error message:
error: scipy 1.5.0 is installed but scipy<1.2 is required by {'platon'}

Is there any way around this? Also, I mainly want to use ExoCTK for limb darkening calculations: is there a simple way to just install that?

Thanks for any help.

**Comment by bourque** [comment]
Hi @thommevans, apologies for taking so long to get into this.  There have been several updates to the ExoCTK software environment since you initially opened this issue, so I think this may be resolved in the latest version.  Please let me know if you are still having an issue with this.  Thank you!
