### ISSUE TITLE
New contamination overlap fails on the web-version with MIRI-LRS or NIRCam

### ISSUE THREAD

**Issue by nespinoza** [ExoCTK/exoctk#416]
Hi folks,

 When trying the new contamination overlap implemented by @jaymedina in our test server, the code fails to perform the calculation for MIRI or NIRCam (works for SOSS!) with the following error:

<img width="654" alt="Screen Shot 2020-09-24 at 3 36 15 PM" src="https://user-images.githubusercontent.com/2046682/94191593-b9365680-fe7b-11ea-93d8-e76f240a6ae3.png">

We reviewed this briefly with @mfixstsci, @hover2pi and @bourque --- this might be an issue with the actual web app perhaps, but we are not sure. Currently @mfixstsci and @hover2pi looking into this, but would be good to know if @jaymedina has any ideas on why this is not working!

N.

**Comment by nespinoza** [comment]
As an update to this: it seems the contamination overlap code is trying to find files that are not on our ExoCTK data files. @jaymedina contacted us internally confirming this, and files will be moved. They have to be added to the Box folder as well!

**Comment by jaymedina** [comment]
Posting my e-mail reply here for record-keeping:

I’m almost certain this is because the new data has not been moved! I modified the NIRCam traces to put them in the correct orientation. The new exoctk_contam data lives here: /user/jmedina/exoctk_data/exoctk_data/exoctk_contam/traces
[...]
 
Please keep me updated on your progress! I will ramp back up on science as soon as I can.
 
Best,
 
Jenny

**Comment by nespinoza** [comment]
All right, this has been fixed!
