### ISSUE TITLE
MIRI and NIRCam contamination overlap times out on web-version

### ISSUE THREAD

**Issue by nespinoza** [ExoCTK/exoctk#418]
Hi everyone,

 When trying to run a MIRI or NIRCam contamination overlap run in the most recent ExoCTK web version, the runs time-out and never finish. There is no error message in the console other than the calculation taking a long time and then just timing out.
 
 Interestingly, this does not happen for NIRISS/SOSS. There it works as good as always!

 I'm assigning @jaymedina to this, as I'm sure she can figure this out faster than any of the rest of us! I'll assign myself and @bourque as well because once that's fixed, we have to updated + deploy to production (which is something either me or Matthew can do I believe).

 Best,
Néstor

**Comment by jaymedina** [comment]
Looks like it ran successfully on my local. I know what the problem is now. It took 10 mins to run :sweat_smile: So it might be that there is a cap for how long a process should run on the web server, and it will abort the process if it goes over minute M.
The new code takes longer to generate a field at every position angle because of all the transformations we have to take the stars thru.
The solution is to run parallel processing (so generate the field for more than one angle at a time). I’m not too familiar with parallel processing but I’ll make an attempt today and keep you updated

![image](https://user-images.githubusercontent.com/32107699/94310505-bc971400-ff47-11ea-9fea-3b65785fef6f.png)

**Comment by jaymedina** [comment]
Line 344 in sossFieldSim.py (https://github.com/ExoCTK/exoctk/blob/master/exoctk/contam_visibility/sossFieldSim.py)
would be the for loop that needs to run Pool
The only thing is, once the field gets generated (a 2d array), it gets placed into the Simulation Cube (a 3d array) in the correct position (so angle 1 goes in index 1, angle 2 goes in index 2, etc…) - does Pool() consider that?

**Comment by jaymedina** [comment]
The test I ran for the screenshot above was done in my Python 3.7 exoctk environment, in which I wrote my code. I recently found out that our production server actually uses a 3.6 environment (see https://github.com/ExoCTK/exoctk/pull/422 for further details). 

IF the server survives the long calculations of the new pySIAF algorithm in fieldSim, this incompatibility issue is the actual culprit of the tool crashing. In which case, just updating the NumPy package on production would fix it.
